name: build
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run : pip install mkdocs >=1.1.2, ==1.1.*
      - run: pip install --force-reinstall mkdocs-material>=5.0.0b2
      - run: pip install pymdown-extensions
      - run: mkdocs gh-deploy --force --clean --verbose
